### ISSUE TITLE
MacOS M1 Max - Incompatible Driver

### ISSUE THREAD

**Issue by josephbharrison** [charles-r-earp/krnl#9]
### Issue
```
thread 'main' panicked at tests/integration_tests.rs:26:58:
called `Result::unwrap()` on an `Err` value: incompatible driver
```
### System Info
- **macOS:** Sonoma 14.2.1
- **GPU:** Apple M1 Max
- **Driver:** MoltenVK 1.2.6
- **Vulkan Instance Version:** 1.3.268
- **rustc:** 1.75.0 (82e1608df 2023-12-21)
- **cargo:** 1.75.0 (1d8b05cdd 2023-11-20)

### `cargo test` Backtrace
```sh
❯ RUST_BACKTRACE=1 cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.05s
     Running unittests src/lib.rs (target/debug/deps/krnl-0b2bd0085789fe49)

running 3 tests
test buffer::tests::buffer_serde_tokens ... ok
test buffer::tests::buffer_serde_bincode2 ... ok
test buffer::tests::buffer_serde_json ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/integration_tests.rs (target/debug/deps/integration_tests-1938f35d405d84a0)
thread 'main' panicked at tests/integration_tests.rs:26:58:
called `Result::unwrap()` on an `Err` value: incompatible driver

Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/backtrace.rs:331:13
   3: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
             at /Users/josephbharrison/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.79/src/error.rs:565:25
   4: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1963:27
   5: <krnl::device::vulkan_engine::Engine as krnl::device::DeviceEngine>::new
             at ./src/device/vulkan_engine.rs:187:13
   6: krnl::device::RawDevice::new
             at ./src/device.rs:336:22
   7: krnl::device::builder::DeviceBuilder::build
             at ./src/device.rs:130:27
   8: integration_tests::main
             at ./tests/integration_tests.rs:26:32
   9: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:154:18
  11: std::rt::lang_start::{{closure}}
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:167:18
  12: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:284:13
  13: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  14: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  15: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  16: std::rt::lang_start_internal::{{closure}}
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:48
  17: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  18: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  19: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  20: std::rt::lang_start_internal
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:20
  21: std::rt::lang_start
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:166:17
  22: _main
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1077:23
   4: integration_tests::main
             at ./tests/integration_tests.rs:26:32
   5: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: test failed, to rerun pass `--test integration_tests`
```

### Vulkan Summary
```sh
❯ vulkaninfo --summary
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.268


Instance Extensions: count = 15
-------------------------------
VK_EXT_debug_report                    : extension revision 10
VK_EXT_debug_utils                     : extension revision 2
VK_EXT_metal_surface                   : extension revision 1
VK_EXT_surface_maintenance1            : extension revision 1
VK_EXT_swapchain_colorspace            : extension revision 4
VK_KHR_device_group_creation           : extension revision 1
VK_KHR_external_fence_capabilities     : extension revision 1
VK_KHR_external_memory_capabilities    : extension revision 1
VK_KHR_external_semaphore_capabilities : extension revision 1
VK_KHR_get_physical_device_properties2 : extension revision 2
VK_KHR_get_surface_capabilities2       : extension revision 1
VK_KHR_portability_enumeration         : extension revision 1
VK_KHR_surface                         : extension revision 25
VK_LUNARG_direct_driver_loading        : extension revision 1
VK_MVK_macos_surface                   : extension revision 3

Instance Layers: count = 5
--------------------------
VK_LAYER_KHRONOS_profiles         Khronos Profiles layer         1.3.268  version 1
VK_LAYER_KHRONOS_shader_object    Khronos Shader object layer    1.3.268  version 1
VK_LAYER_KHRONOS_synchronization2 Khronos Synchronization2 layer 1.3.268  version 1
VK_LAYER_KHRONOS_validation       Khronos Validation Layer       1.3.268  version 1
VK_LAYER_LUNARG_api_dump          LunarG API dump layer          1.3.268  version 2

Devices:
========
GPU0:
        apiVersion         = 1.2.268
        driverVersion      = 0.2.2014
        vendorID           = 0x106b
        deviceID           = 0xe0203ef
        deviceType         = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
        deviceName         = Apple M1 Max
        driverID           = DRIVER_ID_MOLTENVK
        driverName         = MoltenVK
        driverInfo         = 1.2.6
        conformanceVersion = 0.0.0.0
        deviceUUID         = 0000106b-0e02-03ef-0000-000000000000
        driverUUID         = 4d564b00-0000-27de-0e02-03ef00000000
```

This would be *amazing* if I could get this working. Awesome project!🫡

**Comment by charles-r-earp** [comment]
> ### Issue
> 
> ```
> thread 'main' panicked at tests/integration_tests.rs:26:58:
> called `Result::unwrap()` on an `Err` value: incompatible driver
> ```

Pretty sure that VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR needs to be set as explained [here](https://github.com/KhronosGroup/MoltenVK/blob/main/Docs/MoltenVK_Runtime_UserGuide.md#interaction) so let me know if #10 helps!

> 
> This would be _amazing_ if I could get this working. Awesome project!🫡

Thanks!

**Comment by josephbharrison** [comment]
Yep, that did it!

```sh
❯ cargo test --test integration_tests -- --exact none
   Compiling krnl v0.0.4-alpha (/Users/josephbharrison/code/krnl)
    Finished test [unoptimized + debuginfo] target(s) in 3.73s
     Running tests/integration_tests.rs (target/debug/deps/integration_tests-1938f35d405d84a0)
devices: [
    DeviceInfo {
        index: 0,
        name: "Apple M1 Max",
        device_id: 235013103,
        vendor_id: 4203,
        max_groups: 1073741824,
        max_threads: 1024,
        subgroup_threads: 32,
        features: Features {
            shader_int8: true,
            shader_int16: true,
            shader_int64: true,
            shader_float16: true,
            shader_float64: false,
        },
        debug_printf: false,
    },
]
KRNL_DEVICE = Err(NotPresent)
testing device 0

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 604 filtered out; finished in 0.00s
```
Thanks for the quick response!

**Comment by josephbharrison** [comment]
There are other test issues. But I'll open those separately, as needed. Thanks for the help.
